### ISSUE TITLE
How to pass additional parameters?

### ISSUE THREAD

**Issue by LeJav** [jonatanklosko/material-ui-confirm#1]
Hello,
Thanks you for your work on this HOC, I find it very useful and easy to use.
But I have a problem in my environment. I want to use it to validate action in a material-ui table (https://material-table.com/#/docs/features/actions). The onClick event passes 2 arguments: event and data about the row.
Here is an example which is working:
    onClick: (e, rowData) => {console.log(e); console.log(rowData)} 
I would like to use confirm for this action.
But when doing:
  onClick: props.confirm((e, rowData) => {console.log(e); console.log(rowData)}, { description: "salut" })
the confirmation dialog opens correctly, the 'e' parameter is correctly logged (but I think it is the event from the OK button, not my action button), but I have undefined for rowData: it is not passed to my callback function.
Is it possible to get the onClick arguments to my callback function?

Thanks for your help.

**Comment by jonatanklosko** [comment]
Thanks for reporting! Fixed in 746e1333941d1d6d2d69986913885a6d242fbaf5 and published as 1.0.2.

**Comment by LeJav** [comment]
Many thanks for your quick fix!


Le 31/12/2019 à 14:18, Jonatan Kłosko a écrit :
