### ISSUE TITLE
Getting `Uncaught (in promise)` whenever the confirm is cancelled

### ISSUE THREAD

**Issue by alexweber** [jonatanklosko/material-ui-confirm#10]
Steps to replicate: follow the setup instructions...

**Comment by jonatanklosko** [comment]
Well, that's by design, user answer is represented as a promise, so you can handle it in a standardized manner. Any particular problem with that?

**Comment by alexweber** [comment]
> Well, that's by design, user answer is represented as a promise, so you can handle it in a standardized manner. Any particular problem with that?

yeah, catching it doesn't seem to work, neither does wrapping it in a try block.  error is always going to console.

**Comment by jonatanklosko** [comment]
> catching it doesn't seem to work

Hmm, I've just generated a new project and the following catches the error just fine for me:

```js
confirm().then(...).catch(() => {});
```

[Here](https://codesandbox.io/s/material-ui-confirm-demo-hvk1w)'s a demo with an example handler, is that how you use it?

**Comment by jonatanklosko** [comment]
Any updates on that?

**Comment by alexweber** [comment]
i must have been doing something wrong :)
