### ISSUE TITLE
confirm function: input value remains in the TextField after the dialog is closed

### ISSUE THREAD

**Issue by telekosmos** [jonatanklosko/material-ui-confirm#102]
Related to #89 , but when using the `confirm` function from the hook with `confirmationKeyword` 
```
const confirm = useConfirm();
// ...
confirm({
  title: 'TITLE',
  description: (
    <Typography>
      Please enter{' '}
      <Typography component="span" sx={{ fontWeight: 700 }}>
        {props.row.displayName}
      </Typography>{' '}
      in the input field.
    </Typography>
  ),
  confirmationKeyword: props.row.displayName,
})
// ...
```

Steps to reproduce:
- open confirm dialog
- input some text in the rendered textfield
- click either Cancel or Ok (if your input the matches `confirmationKeyword`
- open again
- you see the same text typed before in the textfield
- *expected result*: to have the textfield blank on second open.

Thanks for the great job!

**Comment by jonatanklosko** [comment]
Hey @telekosmos, are you using v3.0.16? I can't reproduce.

**Comment by telekosmos** [comment]
Yes, I explicitly updated to 3.0.16 (latest I guess).

I found out the issue is missing if I try the app in a **private window**... so some sort of cache issue was misleading. Sorry about the false positive, shame on me.

Closing this.
