### ISSUE TITLE
Question - Is there an easy way to show a close button?

### ISSUE THREAD

**Issue by josoroma** [jonatanklosko/material-ui-confirm#11]
![image](https://user-images.githubusercontent.com/69951/76661744-cf18a580-6541-11ea-8d45-d95d968562e0.png)

oops one more question:

How can close the dialog if the user clicks the area outside the modal itself (the grey part).

Thanks a bunch!

**Comment by jonatanklosko** [comment]
Currently there is no easy way to show the cancellation icon. This could be an option, but the idea is that the two buttons are cancel/ok respectively. If you change the cancellation text to something else, it's still supposed to behave like cancellation. For a more complex example I'd suggest a custom dialog instead.

As for the click-cancellation this is actually the default behavior, doesn't it work for you?

**Comment by josoroma** [comment]
@jonatanklosko the module is awesome, but today come up this new requirement, so if UX approves it, I probably will end up forking this module and adding that button I guess.

Thanks!

**Comment by tincho** [comment]
@josoroma hey! did you make that fork? I'm also considering to do it
