### ISSUE TITLE
confirm is not a function

### ISSUE THREAD

**Issue by tabrezansari** [jonatanklosko/material-ui-confirm#12]
i installed this in react with typescript its says confirm is not a function

**Comment by jonatanklosko** [comment]
Is it a Typescript error or a runtime one? Did you wrap your app in `ConfirmProvider` as described [here](https://github.com/jonatanklosko/material-ui-confirm#usage)?

**Comment by llaidie** [comment]
Hello  same issue

**Comment by jonatanklosko** [comment]
Any chance for you to reproduce the issue? I've just created a TS demo analogous to the one from README [here](https://codesandbox.io/s/material-demo-tsg14).

**Comment by usmansabir98** [comment]
same issue. I am using react hooks but the suggested method is not working

**Comment by CycoPH** [comment]
Can you post some code where you are getting the error. Its easier to help then

**Comment by tabrezansari** [comment]
> i installed this in react with typescript its says confirm is not a function
