### ISSUE TITLE
Allow ReactNode instead of string in options

### ISSUE THREAD

**Issue by lkostrowski** [jonatanklosko/material-ui-confirm#14]
https://github.com/jonatanklosko/material-ui-confirm/blob/c9c7f0535b7105c29f418a62d116d26d64829c37/src/index.d.ts#L6

Hi, I find your lib very useful, thanks :) 

There is small improvement with zero-cost. Instead of forcing string for title, description etc it should accept ReactNode, so I can inject `<Typography>` or other formatted node.

I you agree I can make a PR

**Comment by jonatanklosko** [comment]
Makes perfect sense, thanks! Changed in 0b7ae0da2ba28391743450561d3fb7ec3c0990b6 and published as `2.0.5`.

**Comment by lkostrowski** [comment]
You should probably update the readme ;) Thanks!
