### ISSUE TITLE
Demo errors on cancel

### ISSUE THREAD

**Issue by mattcorner** [jonatanklosko/material-ui-confirm#15]
Demo errors on cancel (albeit only in development) due to unhandled promise rejection. May be worth adding a `.catch(() => console.log("User cancelled"))`?

I see the same problem mentioned in the issues list so probably worth documenting.

**Comment by jonatanklosko** [comment]
Ah yeah, I agree it's quite confusing for a demo to error like that, so I just went forward with your suggestion. Thanks!
