### ISSUE TITLE
feature request: close the modal without cancel / confirm action

### ISSUE THREAD

**Issue by tincho** [jonatanklosko/material-ui-confirm#17]
hello! 

we've been using this lib but found that, when clicking in the backdrop to close the modal, 

the promise is rejected: so it's like clicking the `cancellationButton`

we'd like to have a neutral option to close the modal as if nothing happened

(maybe will submit a PR if doesn't take too long to fix)

**Comment by jonatanklosko** [comment]
Hey! I think it would indeed be a more intuitive behavior.

**Comment by jonatanklosko** [comment]
Published as `2.1.1`, thanks!
