### ISSUE TITLE
[FEAT] Possible to add keypress listeners?

### ISSUE THREAD

**Issue by walmat** [jonatanklosko/material-ui-confirm#19]
Hi there! First off, thanks for the amazing hook into the MUI's dialog component! I've been using this in a lot of my UI and have zero problems with it.

One thing I ended up doing on my own was wrapping the confirmation in a keypress listener, so that it would confirm the dialog if the user presses enter (or another key of my choice). I feel like this would be a great addition to this as it improves UX a bit. If you'd like, I can submit a PR and you can look it over and tell me what you think.

Anyways, thanks again for putting this together! Have a great day 😄

**Comment by josiahayres** [comment]
An even easier solution would be to add the `autoFocus` prop onto the submit button, like how the team have done with the demo at: https://material-ui.com/components/dialogs/#alerts

**Comment by jonatanklosko** [comment]
@josiahayres that's a good point! Using this approach it's actually possible to configure the behavior globally ([demo](https://codesandbox.io/s/material-ui-confirm-demo-forked-6lwip?file=/src/App.js)). @walmat does that remove the need for your wrapper?

**Comment by jonatanklosko** [comment]
@walmat I've just added a [new section](https://github.com/jonatanklosko/material-ui-confirm#useful-notes) in readme, hopefully it does the job =)
