### ISSUE TITLE
Usage with Hooks

### ISSUE THREAD

**Issue by Cristy94** [jonatanklosko/material-ui-confirm#2]
Can `material-ui-confirm` used in functional components?

Why is `withConfirm` needed? Can't there just be a global "confirm" function?

**Comment by jonatanklosko** [comment]
It sure can, the example in README actually shows a functional component.

`withConfirm` is just a higher order component that is used to add a dialog alongside the wrapped component and open it whenever you call the `confirm` function added to the wrapped component props.

I do however plan to play around with turning this into hooks-based version that would require adding a context provider once and using `const confirm = useConfirm();` whenever needed;

**Comment by jonatanklosko** [comment]
I've just released v2, which makes full use of hooks! It's definitely cleaner and more flexible now.

**Comment by Cristy94** [comment]
Nice, great job!
