### ISSUE TITLE
Enable Prevent Dialog Close

### ISSUE THREAD

**Issue by stefensuhat** [jonatanklosko/material-ui-confirm#24]
Hi,

I've tried found a way how to prevent the dialog box to close upon "OK" button is clicked (waiting for API call done then will manually trigger the dialog to closed). 

Is this feature available?

**Comment by jonatanklosko** [comment]
The button is controlled by this package and works synchronously. This seems like a case that needs more customization, perhaps [this comment](https://github.com/jonatanklosko/material-ui-confirm/issues/22#issuecomment-743936227) will help.

**Comment by jonatanklosko** [comment]
Clicking either button resolves the promise and only then the user callback is invoked, at which point we are closing the dialog. I don't think we can easily support asynchronous actions with the current API.
