### ISSUE TITLE
Options to add extra dialog action buttons?

### ISSUE THREAD

**Issue by imjordanxd** [jonatanklosko/material-ui-confirm#26]
Would it be possible to have the ability to add extra action buttons? I know that "cancel" will reject the promise and "confirm" will resolve, could bind any additional buttons to resolve/reject and the resolved/rejected promise could be a value indicating which action was pressed?
I mainly had the motivation of a dialog with options "Yes", "No" and "Cancel".

**Comment by jonatanklosko** [comment]
I think generally more than 2 buttons for closing the modal are not a good idea and this doesn't fit into the current approach (which is indeed limited to maximally streamline the common use case). In your case you'd need more customisation, perhaps [this](https://github.com/jonatanklosko/material-ui-confirm/issues/22#issuecomment-743936227) comment helps.

**Comment by jonatanklosko** [comment]
As mentioned, I think this is out of the scope of this package and for more customization I suggest the other approach.
