### ISSUE TITLE
Usage as a prompt, get input string from user

### ISSUE THREAD

**Issue by Cristy94** [jonatanklosko/material-ui-confirm#3]
Can this be used/modified to show a **prompt** modal (with text input) instead of just confirm buttons?

So `confirm.then((response) => {})` would receive the string the user entered in `response`.

**Comment by jonatanklosko** [comment]
Honestly, I think input dialogs are rarely simple text **prompt**s (cannot think of one time I needed that ^^). It's usually a custom field or a whole form and I'd say generalizing those doesn't make much sense as it's better to have full control in those cases.

May consider this if there's a strong support for it, but for now I think it doesn't really makes sense.

**Comment by el1f** [comment]
Chiming in to suggest a possible use case that I feel is fairly common and would warrant such a change: You often want to ask users to at least provide a simple validation for their action (think Github's deletion prompt, where it asks you to input the repo's name to delete it) to allow the action's submission.

**Comment by CycoPH** [comment]
I've tried to get this functionality working in the material-ui-confirm-reason package.  Based on this package with a reason field and some validation code added

**Comment by wowczarczyk** [comment]
I came up with a workaround solution using `useRef` hook:

```typescript
export const useSelectDoctor = (
  descriptionKey = 'dialogs.doctor.remove.selectOtherDoctorLabel',
  titleKey = 'dialogs.doctor.remove.title',
): (() => Promise<Doctor | undefined>) => {
  const confirm = useConfirm();
  const { t } = useTranslation();
  const selectedDoctor = useRef<Doctor>();

  const onSubmit = (data?: { doctor: Doctor }) => {
    selectedDoctor.current = data?.doctor;
  };

  return async () => {
    await confirm({
      title: t(titleKey),
      description: (
        <>
          <Typography variant="body2">{t(descriptionKey)}</Typography>
          <Form<{ doctor: Doctor }> onSubmit={onSubmit} noElevation>
            <DoctorAutocomplete submitOnChange={onSubmit} />
          </Form>
        </>
      ),
      cancellationText: t('confirmationDialog.action.cancelButton'),
      confirmationText: t('confirmationDialog.action.confirmButton'),
    });
    return selectedDoctor.current;
  };
};

The `Form` component is just a wrapper around a basic `html` form with react-hook-form used as the controlling library
