### ISSUE TITLE
Option to not use `DialogContentText`

### ISSUE THREAD

**Issue by joshkel** [jonatanklosko/material-ui-confirm#31]
I have a slight variation from useConfirm's normal use case: I'd like to show two paragraphs instead of one. When I do this, React gives a `validateDOMNesting` warning, because the `<p>` elements that I'm using are part of the `DialogContentText` that material-ui-confirm uses.

I understand the [desire](https://github.com/jonatanklosko/material-ui-confirm/issues/22#issuecomment-743936227) to not complicate material-ui-confirm with a bunch of extra options, but what about an option to control the use of `DialogContentText`? I could imagine one of the following:

* A `text` boolean option, defaulting to true; if true, it wraps `description` in `<DialogContentText>`, and if false, it uses it directly.
* A `Text` component prop, defaulting to `DialogContentText`. Callers could override it if desired. (This may be less convenient, since for a lot of purposes, it would need to be an otherwise spurious `div`.)
* A optional `content` ReactNode prop that, if present, completely replaces `<DialogContentText>{description}</DialogContentText>`.

This would also address [this comment](https://github.com/jonatanklosko/material-ui-confirm/issues/21#issuecomment-780286113).

**Comment by jonatanklosko** [comment]
Option 3. sounds good to me, implemented in b8c3ff1f382431181386ecb27522a58070bc425a.

**Comment by joshkel** [comment]
Thanks!
