### ISSUE TITLE
The `title` option dose not support `ReactNode` Object

### ISSUE THREAD

**Issue by chenlein** [jonatanklosko/material-ui-confirm#33]
https://github.com/jonatanklosko/material-ui-confirm/blob/d2b47d4090050a40141968073254896610a6a90e/src/ConfirmationDialog.js#L24

**Comment by jonatanklosko** [comment]
I believe it actually supports `ReactNode`. For example, you can do:

```js
confirm({
  title: <div style={{color: "red"}}>You sure?</div>
})
```
