### ISSUE TITLE
Material UI 5.0 Support?

### ISSUE THREAD

**Issue by dezoito** [jonatanklosko/material-ui-confirm#35]
Material UI 5.0 includes some package renaming from @material-ui/* to @mui/*.

Are there any plans to support Material UI 5.0 instead of the older versions?

Thank you!

**Comment by tifosiblack** [comment]
I can take care of this, and provide a PR.

**Comment by tifosiblack** [comment]
Et voilà : https://github.com/jonatanklosko/material-ui-confirm/pull/36

**Comment by jonatanklosko** [comment]
Closed via #36, thanks @tifosiblack. Published as v3.0.0.

**Comment by dezoito** [comment]
Thank you, gentlemen!

**Comment by tifosiblack** [comment]
You're welcome. That's a library I use a lot, it's normal to contribute ^^
