### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by Cristy94** [jonatanklosko/material-ui-confirm#4]
Any plans to add TypeScript definitions?

I quickly created some that I use in my project:

```
declare module 'material-ui-confirm' {
    export const ConfirmProvider: React.ComponentClass;
    export const useConfirm: () => (options: {
        title?: string;
        description?: string;
        confirmationText?: string;
        cancellationText?: string;
        dialogProps?: Object;
    }) => Promise<any>;
}
```

**Comment by jonatanklosko** [comment]
I've just added [type declarations](https://github.com/jonatanklosko/material-ui-confirm/blob/master/src/index.d.ts) and published as v2.0.2. Let me know if there are any issues!
