### ISSUE TITLE
Returns Boolean Interface

### ISSUE THREAD

**Issue by moomoolive** [jonatanklosko/material-ui-confirm#41]
I recently found this projects and I'm loving how convenient it is to use! Thanks for create such a marvellous library.

I do have one suggestion, which is to provide some sort of API that returns a boolean instead of undefined. In other words,  a function similar to window.confirm which would Promise.resolve(true) on confirm and Promise.resolve(false) on cancel or click away.

I'm imagining something like this:

```
import React from 'react';
import Button from '@mui/material/Button';
import { useConfirm } from 'material-ui-confirm';

const Item = () => {
  // the new proposed API
  const confirm = useConfirm().confirmBool;

  const handleClick = async () => {
    const consent = await confirm({ title: "Are you a duck?" });
    if (!consent) return;
    console.log("you're a duck");
  };

  return (
    <Button onClick={handleClick}>
      Click
    </Button>
  );
};

export default Item;
```

Would love to hear your thoughts

**Comment by jonatanklosko** [comment]
You should be able to create a simple wrapper to achieve that behaviour, try something like this:

```js
function useConfirmCustom() {
  const confirm = useConfirm();

  return useCallback((...args) => {
    return confirm(...args).then(() => true).catch(() => false);
  }, [confirm]);
}
```

You can then put it into a file and even import as `useConfirm` in your components.

It's been a while, so let me know if I miss something :)

**Comment by moomoolive** [comment]
That's true I could do that, but I'd have to create a function like that in every component that uses it (which would be a little tedious). Or am I missing something?

Also, this whole proposed change could be simply made as an option called returnsBool or something
```
confirm({ title: "Are you a duck?", returnsBool: true });
```

**Comment by jonatanklosko** [comment]
Nono, my point is that you can do this:

**hooks/useConfirm.js**
```js
export default function useConfirmCustom() {
  const confirm = useConfirm();

  return useCallback((...args) => {
    return confirm(...args).then(() => true).catch(() => false);
  }, [confirm]);
}
```

**components/MyComponent.js**
```jsx
import useConfirm from "../hooks/useConfirm";

function MyComponent(props) {
  const confirm = useConfirm();

  const handleClick = async () => {
    const consent = await confirm({ title: "Are you a duck?" });
    if (!consent) return;
    console.log("you're a duck");
  };

  return (...);
}
```

---

I think this kind of customization can be left to the user.

**Comment by moomoolive** [comment]
Ha! Okay I tried that initially without useCallback (I'm relatively new to react)

**Comment by moomoolive** [comment]
Can confirm that this works. Thanks for all the help

**Comment by wladimir-k-m** [comment]
If anyone finds this info, keep in mind that the suggestion proposed by @jonatanklosko doesn't really solve the issue since confirm does not resolve nor reject when the user clicks outside of the dialog to dismiss it. In this case the await hangs indefinitely. This obviously is an issue if you have to reset some state after the await.

**Comment by jonatanklosko** [comment]
I've just published v4 with a new Promise API. See [the changelog](https://github.com/jonatanklosko/material-ui-confirm/blob/master/CHANGELOG.md#400) for more information.
