### ISSUE TITLE
Refuse to use reject  to not wrap the code into try catch

### ISSUE THREAD

**Issue by victor-shelepen** [jonatanklosko/material-ui-confirm#43]
Let's always use resolve with a value to avoid "try/catch"  for disagree state. There is an example https://stackblitz.com/edit/react-bueac8 .

The latest version 3 fails on my side.

**Comment by jonatanklosko** [comment]
Hey @victor-shelepen! This is expected, it's designed more towards using `Promise.then` and optionally `Promise.catch`. If you rather use `await` and prefer a boolean you can create a simple wrapper hook, see https://github.com/jonatanklosko/material-ui-confirm/issues/41#issuecomment-980782976 :)

**Comment by gandhis1** [comment]
@jonatanklosko I think your suggestion is reasonable, but currently the return is `Promise<void>`. So a `boolean` would be no worse than the existing return type, and presumably would be backwards-compatible. Is there any reason why you wouldn't just want to make it a `Promise<boolean>` by default? It would save people using `async/await` control flow from some boilerplate.

**Comment by jonatanklosko** [comment]
@gandhis1 this is a breaking change, because the returned promise currently rejects on cancel and the alternative API would be to resolve it with false. In retrospect always resolving with some value would be better, but at this point I don't think it's worth a breaking change.
