### ISSUE TITLE
Is there a way to disable closing popup on backdrop click?

### ISSUE THREAD

**Issue by olhapi** [jonatanklosko/material-ui-confirm#44]
Is there a way to disable closing popup on backdrop click? I've played with dialogProps onClose method but that doesn't helped.

**Comment by jonatanklosko** [comment]
Hey! I don't think it's possible with the current API, backdrop click causes dialog `onClose` similarly to escape and in that case we just close the dialog neither rejecting nor resolving the promise. What's the use case here?

**Comment by olhapi** [comment]
Hello there. Thanks for reply.

When user is required to make a decision it's crucial to prevent dialog being accidentally closed after click on backdrop.

**Comment by jonatanklosko** [comment]
Just added `allowClose` option, so you can set `allowClose: false`, hence requiring the user to either cancel or confirm. Released as 3.0.3 :)

**Comment by olhapi** [comment]
@jonatanklosko  thank you very much! 

Happy holidays 🎉🍾

**Comment by jonatanklosko** [comment]
@olhapi thanks, have a good one too! :rocket:
