### ISSUE TITLE
Opening dialog messes up theme

### ISSUE THREAD

**Issue by DMLON** [jonatanklosko/material-ui-confirm#48]
Hello, i'm trying to use this tool, but every time the confirm function is called, all of my website theme goes to default and i have to reload the website, any ideas what is going on?

EDIT: Cloning the repo and using the files directly works, i'm guessing it's an issue with the npm build using old material ui files (As far as i read this is an issue with material ui https://github.com/mui-org/material-ui/issues/26452 )

**Comment by jonatanklosko** [comment]
Hey @DMLON, did you place `ConfirmProvider` inside `ThemeProvider`?

**Comment by DMLON** [comment]
Yeah, tried it both inside and outside, had the same effect

**Comment by jonatanklosko** [comment]
Note that material-ui-confirm 3 is compatible with Material UI 5 and material-ui-confirm 2 with Material UI 4. Since you pointed out the Material UI issue, I don't think there's much we can do on this side, so I'm gonna close this, feel free to reopen if that's not the case :)
