### ISSUE TITLE
Incorrect version 2.1.4

### ISSUE THREAD

**Issue by umerfaruk** [jonatanklosko/material-ui-confirm#49]
Latest release has a [version number 2.1.4 on npm](https://www.npmjs.com/package/material-ui-confirm/v/2.1.4) which is lower than last release (3.03). The latest version should be 3.0.4 or later.
Can this be fixed?

**Comment by jonatanklosko** [comment]
Hey @umerfaruk! Good catch, v2.1.4 was indeed the last published version (with a feature backported for mui4 compatibility), but v3.0.3 is definitely the latest. I've just manually update the tag with `npm dist-tag add material-ui-confirm@3.0.3 latest` :)

**Comment by umerfaruk** [comment]
Thanks for the prompt resolution @jonatanklosko
