### ISSUE TITLE
[Enhancement] Add variant & color to action button

### ISSUE THREAD

**Issue by stefensuhat** [jonatanklosko/material-ui-confirm#5]

**Comment by jonatanklosko** [comment]
I've just added `confirmationButtonProps` and `cancellationButtonProps` to the options, see an example here: https://github.com/jonatanklosko/material-ui-confirm/blob/c9c7f0535b7105c29f418a62d116d26d64829c37/stories/index.stories.js#L65-L69

*Note: if you want to override the props app-wide, you can pass `defaultOptions` to the `ConfirmProvider`.*

Implemented in 1a54b9937720e427de381ce0dc5239ef778f4c3e and published as v2.0.4.

**Comment by bwpedro** [comment]
Hi, is it possible to put custom color? Like if I want to change the color to red, instead of puting secondary or primary. How does it work? Can you provide an example?

**Comment by jonatanklosko** [comment]
@bwpedro you can pass class names to override the default styles as in the [Material UI docs](https://material-ui.com/customization/components/#overriding-styles-with-classes). [Here](https://codesandbox.io/s/material-ui-confirm-demo-pw3dm)'s a demo demonstrating that.
