### ISSUE TITLE
Control to customise DialogActions section

### ISSUE THREAD

**Issue by starlord13599** [jonatanklosko/material-ui-confirm#53]
Hey,
i am looking for a way to customise the DialogActions portion of the modal, as if suppose i want to switch the position of the 'Ok' and 'Cancel' button.... also suppose i want to add a third button in the bottom along with  'Ok' and 'Cancel button', Is there any way to do so??

**Comment by jonatanklosko** [comment]
Hey, see #26. tl;dr this it outside the scope of this project and [here](https://github.com/jonatanklosko/material-ui-confirm/issues/22#issuecomment-743936227) is an alternative approach that allows for arbitrary customization.
