### ISSUE TITLE
Option to pass custom template

### ISSUE THREAD

**Issue by sujeet-agrahari** [jonatanklosko/material-ui-confirm#54]
Currently it only uses Material UI basic dialog. If I want to use Form dialogu, there is no option to pass this template.

Take example of this [pacakge](https://www.npmjs.com/package/react-alert), it accepts a custom template,
```
const Root = () => (
  <AlertProvider template={AlertTemplate} {...options}>
    <App />
  </AlertProvider>
)
```

**Comment by jonatanklosko** [comment]
Hey, you can use `content` for more complex description markup. Use cases like form dialogs are outside the scope of this package, see https://github.com/jonatanklosko/material-ui-confirm/issues/21#issuecomment-1053707437 for an alternative suggestion.
