### ISSUE TITLE
Default options does not update at runtime.

### ISSUE THREAD

**Issue by markocupic024** [jonatanklosko/material-ui-confirm#56]
Hello, I am using i18n for React to change language of my app, but when the language changes confirmationText and cancellationText stay the same: 
`{
      confirmationButtonProps: { autoFocus: true },
      confirmationText: t("dialogs.yes"),
      cancellationText: t("dialogs.no"),
    }`

**Comment by jonatanklosko** [comment]
Hey @markocupic024, sorry for the delayed response! Fixed in 99537a7526bc8d514104d6fa1988d709f7567330 and published as 3.0.5 :)
