### ISSUE TITLE
Control key word for confirm 

### ISSUE THREAD

**Issue by sabotag** [jonatanklosko/material-ui-confirm#57]
Is there a way to add an input to the Confirm Dialog to enter a control word? 
After entering this word, the button will become active.

Thank you

![Screenshot 2022-09-19 at 23 52 51](https://user-images.githubusercontent.com/3120322/191114785-698404dc-4d5c-4695-899f-c0841cec8ed5.png)

**Comment by jonatanklosko** [comment]
Hey @sabotag, this is currently not possible, but I'm open to a PR that adds a feature like this :)

**Comment by sabotag** [comment]
@jonatanklosko ooh, it will be great, it will help us us a lot =)
thank you
