### ISSUE TITLE
Use DialogActions props to add styles

### ISSUE THREAD

**Issue by aminebelmahi** [jonatanklosko/material-ui-confirm#58]
Sometimes we want to pass props to the DialogActions component and add some styles accordingly.

I can contribute with a PR.

**Example:** ![image](https://user-images.githubusercontent.com/63819603/193784637-a562eee9-a14b-4edb-88cd-c0f91c967877.png)

**Comment by jonatanklosko** [comment]
Closed in 2f81a9d0d7ec4a5b124fd1d290a14e0ef81417f5. Released as v3.0.6.
