### ISSUE TITLE
Change the order of buttons

### ISSUE THREAD

**Issue by lashax** [jonatanklosko/material-ui-confirm#67]
Can we change the order of buttons, so the confirmation button would come before the cancellation button? Note that I only want to change their order, both buttons should stay in the bottom right corner like they are now.

**Comment by jonatanklosko** [comment]
There's no such option currently, but a PR adding that is welcome :)

**Comment by MattFellows** [comment]
@jonatanklosko I've got a PR which I beleive resolves this issue :)

**Comment by jonatanklosko** [comment]
Closed in #70.
