### ISSUE TITLE
Closing the confirm should reject the promise

### ISSUE THREAD

**Issue by Amatewasu** [jonatanklosko/material-ui-confirm#71]
When the option `allowClose` is set to `true` (default value), the promise should be rejected (like if the user pressed the cancel button) when the confirm is closed (by pressing the Escape key for instance).

Currently, the promise keep its pending state.

**Comment by Amatewasu** [comment]
https://github.com/jonatanklosko/material-ui-confirm/blob/ae074b2ce941ddfabbe4881b376dfba83fa987e3/src/ConfirmProvider.js#L83-L92

Maybe we can replace the following line:

https://github.com/jonatanklosko/material-ui-confirm/blob/ae074b2ce941ddfabbe4881b376dfba83fa987e3/src/ConfirmationDialog.js#L90

with `onClose={allowClose ? handleReject : null}`?

**Comment by Amatewasu** [comment]
Thank you for your answer. I didn't see the conversations and I fully understand the choice.

Just my thinking if it were me: rejecting the promise on close but with a different error. Thereby we could do this to discriminate the effect:
```js
try {
  confirm({ opts });
} catch (e) {
  if (e instanceof ConfirmClose) {
    console.log('Escape key pressed');
  } else if (e instanceof ConfirmCancel) {
    console.log('Cancel pressed');
  }
}
```

**Comment by jonatanklosko** [comment]
Yeah could also be that, but I think it's fine and I'd rather avoid a breaking change :)

**Comment by TeoAvignon** [comment]
It would be a great idea with the props! 
- No breaking change
- a new feature
