### ISSUE TITLE
What version should I use for MUI v4?

### ISSUE THREAD

**Issue by dimafrontdev** [jonatanklosko/material-ui-confirm#76]
Is there a way to use the latest version with all the new props for confirm but using the mui v4 at the same time?

**Comment by jonatanklosko** [comment]
Hey, v3.x.y of this packages is only compatible with MUI v5, so for MUI v4 you need v2.x.y and the more recent features are not available. I happily accept contributions with new options, but I don't have the capacity to maintain separate versions for both MUI v4 and v5 :)
