### ISSUE TITLE
Suggestion - add result in promise

### ISSUE THREAD

**Issue by guicompeng** [jonatanklosko/material-ui-confirm#78]
Thanks for the library! I liked very much.

I would like to suggest, to add the result of user action, instead of staying in .then and .catch. It is very common to forget to add .catch, as it is common to do nothing when the user clicks "cancel". So I am always forced to add the code ".catch(() => {});"

The module sweetalert2 does this.

What do you think?

**Comment by jonatanklosko** [comment]
Hey @guicompeng! This is intentional, it allows to distinguish between explicit cancel and natural close like Escape or backdrop click (in which case the promise neither resolves nor rejects). If you want a different behaviour you can create a simple wrapper with the desired behaviour, for example https://github.com/jonatanklosko/material-ui-confirm/issues/41#issuecomment-980782976 shows how to resolve with a boolean instead of rejecting :)

**Comment by guicompeng** [comment]
The way you suggested worked, thanks!
I'm used to sweetalert2, then we can differentiate Escape or backdrop differently, for the same "result". The result is an object that contains many details of what was done:
result has: isConfirmed, isDenied, isDismissed, value, dismiss.
and in "dismiss" contains the reason for cancellation.

I understand that the proposal is different, and anyway, your suggestion has already helped, thank you.

**Comment by jonatanklosko** [comment]
I can see that making sense yeah, but at this point I don't think it's worth a breaking change :)

**Comment by wladimir-k-m** [comment]
> Hey @guicompeng! This is intentional, it allows to distinguish between explicit cancel and natural close like Escape or backdrop click (in which case the promise neither resolves nor rejects). If you want a different behaviour you can create a simple wrapper with the desired behaviour, for example [#41 (comment)](https://github.com/jonatanklosko/material-ui-confirm/issues/41#issuecomment-980782976) shows how to resolve with a boolean instead of rejecting :)

Promises that never resolve are bad practice since the code after the await (or `then`) will never be executed. The name "promise" suggests that it should always resolve as promised.
It also does not allow to distinguish between close and cancel because close can't be detected.

**Comment by MichaelDimmitt** [comment]
> I can see that making sense yeah, but at this point I don't think it's worth a breaking change :)

what if we put it behind a feature flag?
this material-ui-confirm is configurable and does almost everything right except for this detail.

**Comment by jonatanklosko** [comment]
I've just published v4 with a new Promise API. See [the changelog](https://github.com/jonatanklosko/material-ui-confirm/blob/master/CHANGELOG.md#400) for more information.
