### ISSUE TITLE
Q: how to add form fields + read them after OK is pressed?

### ISSUE THREAD

**Issue by gvdhoven** [jonatanklosko/material-ui-confirm#79]
Would it be (relatively) easy to add a form (text-field + checkbox) to the Confirmbox?
If so, how would you be able to read the properties entered in the form fields?
Could you add a simple example to the readme.md if that would be possible?

**Comment by jonatanklosko** [comment]
Forms are outside of the scope of this package, see https://github.com/jonatanklosko/material-ui-confirm/issues/69#issuecomment-1420549813 :)
