### ISSUE TITLE
Providing a Static Method for Easy Use Without Hooks, Suitable for Class Component Projects

### ISSUE THREAD

**Issue by liaokaime** [jonatanklosko/material-ui-confirm#85]
Is it possible to provide a static method that can be used as easily as using an alert, without the need for hooks? This is because many projects use class components. By the way, the latest version of Notistack (3.x) provides static methods.

**Comment by jonatanklosko** [comment]
If someone wants to explore this direction, a PR is welcome, provided it doesn't introduce much complexity.

**Comment by liaokaime** [comment]
I have created a [PR here](https://github.com/jonatanklosko/material-ui-confirm/pull/86)

**Comment by jonatanklosko** [comment]
Closed in #86.
