### ISSUE TITLE
Asynchrounous Confirm Suggestion

### ISSUE THREAD

**Issue by ZiedChekir** [jonatanklosko/material-ui-confirm#87]
Is there a mechanism to implement asynchronous confirmation? For instance, when a user initiates the deletion of an item, a confirmation dialog appears. Upon the user's confirmation, the button transitions to a loading state, a request is sent to the backend, and the system awaits a response. Upon successful completion, the dialog closes. This is really beneficial to include Promises in the confirm component.

**Comment by jonatanklosko** [comment]
Hey, I think this is outside the scope of this package, see #24.
