### ISSUE TITLE
Allow `data-attributes` on `dialogProps`

### ISSUE THREAD

**Issue by apdrsn** [jonatanklosko/material-ui-confirm#88]
Hi and thanks for this library,
It seems I am not able to add a `data-attribute` to `dialogProps`. I would like that for testing purposes.
It's giving me a TS-error.
Like this:
![image](https://github.com/jonatanklosko/material-ui-confirm/assets/6361772/30a7d822-8319-4538-85ab-133ee7d73e08)
 Have I missed something in the docs?

**Comment by jonatanklosko** [comment]
The `DialogProps` type comes directly from MUI. See https://github.com/mui/material-ui/issues/33175. You may be able to define the `DialogProps` interface with just `data-automation-id` and it should effectively merge with the existing interface.
