### ISSUE TITLE
Test with Enzyme

### ISSUE THREAD

**Issue by Look-in** [jonatanklosko/material-ui-confirm#9]
Dialog works excellent. Thanks.
But if to test connected with redux component via enzyme, simulating a "button click" returns an error:
 TypeError: confirm is not a function

**Test:**
const wrapper = shallow(<Container store={store} />)
    .find('ItemPage')
    .dive();
wrapper
            .find('[aria-label="delete"]')
            .find(`[value="${id}"]`)
            .simulate('click', {
                currentTarget: {
                    value: id
                }
            });

Wrapping with <ConfirmProvider> e.g.   shallow(<ConfirmProvider><Container store={store} .../>) has no effect

**Comment by jonatanklosko** [comment]
Hey, do you wrap the tested component in `ConfirmPovider`? If not, `useConfirm()` would indeed return undefined (i.e. the `confirm` is undefined).

**Comment by Look-in** [comment]
Hey, do you wrap the tested component - this is not a good solution for me, because all other tests will fail.
I found solution - mock npm module. Created test/__mocks__/material-ui-confirm.js file with 

const useConfirm = () => () => Promise.resolve();
export { useConfirm };

and add async - await to the test:  
it('delete button test', **async** () => {
**await** wrapper.find('...').simulate('click');
expect(store.dispatch).toHaveBeenCalledTimes(1);

Thanks, for quick response.

**Comment by Look-in** [comment]
Solved
