### ISSUE TITLE
Executing navigate in the then method may result in confirm not disappearing。  

### ISSUE THREAD

**Issue by OyeHan** [jonatanklosko/material-ui-confirm#95]
Executing navigate in the then method may result in confirm not disappearing。

```javascript
import { useNavigate} from 'react-router-dom';
 const navigate = useNavigate();

  .then(() => {
        navigate();
      })
    
```

**Comment by jonatanklosko** [comment]
I'm not sure why this would happen, it would be helpful if you could reproduce it in a small demo (modifying the CodeSandbox in the readme). You can also try swapping the function calls here:

https://github.com/jonatanklosko/material-ui-confirm/blob/7a7a02c0f2af0e56a7d37cccb29e4106d8685f0c/src/ConfirmProvider.js#L115-L116

and see if that makes a difference.

**Comment by OyeHan** [comment]
I use setTimeout to solve this problem

**Comment by OyeHan** [comment]
I use setTimeOut to solve this problem.
