### ISSUE TITLE
How to close the confirm dialog programmatically?

### ISSUE THREAD

**Issue by khashashin** [jonatanklosko/material-ui-confirm#96]
I use react-router-dom v6 in my project. When the user triggers the confirmation dialog and navigates to another page, the dialog stays open. I was expecting it to close automatically when the user navigates away, as the component it was opened in no longer exists.

**Comment by jonatanklosko** [comment]
This looks the same as #95, again, it would be helpful to have a reproduction in the CodeSandbox demo :)

**Comment by khashashin** [comment]
> it would be helpful to have a reproduction in the CodeSandbox demo

Ok, I'll provide one in few hours, thanks for the feedback

**Comment by khashashin** [comment]
@jonatanklosko Here you go: https://stackblitz.com/edit/vitejs-vite-lnvbjm?file=src%2FHome.jsx

To reproduce:

1. Click "About Page"
2. Click on "Delete" icon
3. Click on "back" browser button

**Comment by khashashin** [comment]
@jonatanklosko the difference with browsers `window.confirm` API is that browser does not allow you to navigate away if there is confirm open :)

**Comment by jonatanklosko** [comment]
> the difference with browsers window.confirm API is that browser does not allow you to navigate away if there is confirm open

Correct, but the browser confirm is synchronous, it blocks JS execution on the page. This component is not designed to replicate `window.confirm`.

> Click on "back" browser button

Ah, so this is actually different from #95. The change in router state is not related to the confirm action at all, so the current behaviour makes sense.

In 3951633c54399dd0fa0025e7b4e450ffff8f5fb0 I changed it such that the component calling `useConfirm` is linked to the confirmation dialog. When the component gets unmounted, the corresponding dialog is closed (but only if it has been open by that specific component). Published in 3.0.13, let me know if it works as expected for you :)

**Comment by khashashin** [comment]
Thank you!
