### ISSUE TITLE
Flash of default dialog content during close

### ISSUE THREAD

**Issue by DuncanMackintosh** [jonatanklosko/material-ui-confirm#99]
Since 3.0.13 the dialog title/contents revert back to their defaults during the out-transition when you close the dialog. It's especially obvious if you're using a custom title but all the customisations are affected.

Demonstration clip (slowed down to 1/3 speed to make it more obvious):
![material-ui-confirm](https://github.com/jonatanklosko/material-ui-confirm/assets/4966417/7ccb6d62-4e2e-483f-91fe-a6f4cd58c8d5)

**Comment by DuncanMackintosh** [comment]
Commit https://github.com/jonatanklosko/material-ui-confirm/commit/ed4097ca47a137fa09fd53b21e3f281226ca3a62 seems to be what introduced this, as using `state==null` to indicate closed means it uses the defaults during the transition.

There's plenty of ways to fix it, I've got a local fork that adds an 'open' flag to state which I'll open a pull request for in a minute, but if you prefer to resolve it another way that's fine too.

**Comment by jonatanklosko** [comment]
Closed in #100.

**Comment by jonatanklosko** [comment]
Published in v3.0.16.
